version: '3.4'

services:
  nginx_block_explorer:
    image: nginx:alpine
    container_name: nginx_block_explorer
    env_file: ./config/network-config.env
    network_mode: bridge
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./certificates:/etc/nginx/certificates:ro
     - ./remme-block-explorer-frontend/build:/root/build
    ports:
     - 80:80
     - 443:443

  remme_block_explorer:
    build: .
    image: remme_block_explorer
    network_mode: service:nginx_block_explorer
    container_name: remme_block_explorer
    depends_on:
      - nginx_block_explorer
